language: go

go:
  - "1.16.x"

install: true

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.38.0


script:
  # run a bunch of code checkers/linters in parallel
  - rm -rf example && golangci-lint run --modules-download-mode=vendor





